// File generated by manual configuration based on Web SDK config.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_gz6lV3ELjOjcFm3Dptrt99INYfVev_I',
    appId: '1:929908901250:web:2423c46bb0f65e12b8fb9b',
    messagingSenderId: '929908901250',
    projectId: 'taskapp-bdb35',
    authDomain: 'taskapp-bdb35.firebaseapp.com',
    storageBucket: 'taskapp-bdb35.firebasestorage.app',
  );

  // NOTA: Estos valores para Android/iOS son aproximados basados en tu config Web.
  // Para que funcionen, debes registrar la app Android/iOS en la consola de Firebase 
  // con el ID: com.example.taskapp
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_gz6lV3ELjOjcFm3Dptrt99INYfVev_I',
    appId: '1:929908901250:android:ce9e8d477e77b47b', // Placeholder
    messagingSenderId: '929908901250',
    projectId: 'taskapp-bdb35',
    storageBucket: 'taskapp-bdb35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_gz6lV3ELjOjcFm3Dptrt99INYfVev_I',
    appId: '1:929908901250:ios:ce9e8d477e77b47b', // Placeholder
    messagingSenderId: '929908901250',
    projectId: 'taskapp-bdb35',
    storageBucket: 'taskapp-bdb35.firebasestorage.app',
    iosBundleId: 'com.example.taskapp',
  );
}
